CATEGORIAS_ALIMENTOS = [
    "Frutas",
    "Grãos",
    "Carnes",
    "Legumes",
    "Vegetais",
    "Processados",
    "Enlatados",
    "Bebidas",
    "Hortifuti",
    "Doces",
    "Laticínios",
    "Condimentos",
    "Temperos",
    "Aperitivos",
    "Congelados",
    "Frios",
]