# Generated by Django 5.1.6 on 2025-05-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='clientuser',
            name='is_client',
        ),
        migrations.AddField(
            model_name='address',
            name='observation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(),
        ),
        migrations.AlterModelTable(
            name='address',
            table='Adress',
        ),
        migrations.CreateModel(
            name='SeparaterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='separater_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SeparaterUser',
            },
        ),
    ]
