# Generated by Django 5.1.6 on 2025-05-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_lote_address_quadra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='object_id',
        ),
    ]
