# Generated by Django 5.1.6 on 2025-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_address_content_type_remove_address_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cep',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='address',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='address',
            name='quadra',
        ),
        migrations.RemoveField(
            model_name='address',
            name='reference',
        ),
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
