# Generated by Django 5.1.6 on 2025-06-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_cep_address_zip_code_remove_address_lote_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
