# Generated by Django 5.1.6 on 2025-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=120)),
                ('completeName', models.CharField(max_length=150, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
