# Generated by Django 5.1.6 on 2025-04-28 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprovante_residencia', models.FileField(upload_to='')),
                ('rg_photo', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('is_deliver', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliver_users',
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
