# Generated by Django 5.1.6 on 2025-05-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_address_content_type_address_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deliveruser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completeName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='client', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
