# Generated by Django 5.1.6 on 2025-05-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_remove_address_content_type_remove_address_user_and_more'),
        ('pedidos', '0003_alter_dadosentrega_endereco_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='DeliverUser',
        ),
    ]
