# Generated by Django 5.1.6 on 2025-05-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supermarket',
        ),
    ]
