# Generated by Django 5.1.6 on 2025-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('categoria', models.TextField()),
                ('marca', models.TextField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_estoque', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=13, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/imagens/')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
