# Generated by Django 5.1.6 on 2025-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_avaliacao_produtos_qtd_avaliacoes_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
