# Generated by Django 5.1.6 on 2025-05-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_avaliacao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avaliacao',
            table='avaliacoes',
        ),
    ]
