# Generated by Django 5.1.6 on 2025-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_avaliacao_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd_avaliacoes',
            field=models.IntegerField(default=0),
        ),
    ]
