# Generated by Django 5.1.6 on 2025-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_produtos_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
