# Generated by Jessé on 2025-05-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_categorias_alter_produtos_categoria'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;")
    ]
