# Generated by Django 5.1.6 on 2025-05-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_run_unaccent_postgres_extension'),
        ('users', '0003_remove_address_content_type_remove_address_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='supermarket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='users.supermarketuser'),
        ),
    ]
