# Generated by Django 5.1.6 on 2025-05-26 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produtos_supermarket'),
        ('users', '0003_remove_address_content_type_remove_address_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='supermarket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='users.supermarketuser'),
        ),
    ]
