# Generated by Django 5.1.6 on 2025-05-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_dadosentrega_pedido_id'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosentrega',
            name='endereco_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='users.address'),
        ),
    ]
