# Generated by Django 5.1.6 on 2025-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_dadosentrega_endereco_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosentrega',
            name='tipo_veiculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
